# Generated by Django 5.0.2 on 2024-02-21 10:09

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(max_length=200, unique=True)),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "last_update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Last updated"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=api.models.gen_invite_code,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Invite code",
                    ),
                ),
                ("used", models.BooleanField(default=False, verbose_name="Used")),
            ],
        ),
        migrations.CreateModel(
            name="GameCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "sex",
                    models.CharField(
                        choices=[(None, "Undefined"), ("MX", "Male"), ("FX", "Female")],
                        default="Undefined",
                        max_length=2,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "register_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.invitecode"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "last_update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Last updated"),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "voting_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.gamecharacter",
                    ),
                ),
                (
                    "voting_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.participant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="gamecharacter",
            constraint=models.UniqueConstraint(
                fields=("game", "name"), name="Ensure unique character name in one game"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("voting_user", "voting_character"),
                name="Ensure only one vote by every user",
            ),
        ),
    ]
