# Generated by Django 5.0.2 on 2024-02-17 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="info_update_time",
        ),
        migrations.AddField(
            model_name="game",
            name="create_time",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
