# Generated by Django 5.0.2 on 2024-02-17 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_game_info_update_time_game_create_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="create_time",
            new_name="create_date",
        ),
    ]
