# Generated by Django 5.0.2 on 2024-02-17 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_create_time_game_create_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="create_date",
        ),
        migrations.AddField(
            model_name="game",
            name="create_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="game",
            name="last_update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
