# Generated by Django 5.0.2 on 2024-02-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_game_create_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="last_update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="Last updated"),
        ),
        migrations.AddConstraint(
            model_name="gamecharacter",
            constraint=models.UniqueConstraint(
                fields=("game", "name"), name="Ensure unique character name in one game"
            ),
        ),
    ]
