# Generated by Django 5.0.2 on 2024-02-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_game_create_time_alter_game_game_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vote",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
