# Generated by Django 5.0.2 on 2024-02-17 12:19

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_vote_score_alter_vote_create_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(default=api.models.gen_invite_code, max_length=20),
                ),
                (
                    "tied_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.participant",
                    ),
                ),
            ],
        ),
    ]
