# Generated by Django 5.0.2 on 2024-02-17 12:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_invitecode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="code",
            field=models.CharField(
                default=api.models.gen_invite_code, editable=False, max_length=20
            ),
        ),
    ]
