# Generated by Django 5.0.2 on 2024-02-17 12:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_remove_invitecode_tied_participant_invitecode_used_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="code",
            field=models.CharField(
                default=api.models.gen_invite_code,
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Invite code",
            ),
        ),
    ]
