# Generated by Django 5.0.2 on 2024-02-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_vote_ensure_only_one_vote_by_every_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="last_update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="Last updated"),
        ),
    ]
